class Constants:
    SYSTEM_SILUX_SABSA = "silux_sabsa"
    SYSTEM_SILUX_COBERTURA = "silux_cobertura"
    SYSTEM_UNIX_SABSA = "unix_sabsa"
    SYSTEM_UNIX_COBERTURA = "unix_cobertura"

    SYSTEM_SOLBEN_SABSA = "sabsa_solben"
    SYSTEM_SOLBEN_COBERTURA = "sabsa_cobertura"

    # Estados
    ESTADO_APROBADO_MA = 9
    ESTADO_OBSERVADO_MA = 10
    ESTADO_LIQUIDADO = 13
    ESTADO_EMPAQUETADO = 15
    ESTADO_ENVIAR_IAFAS = 16
    ESTADO_FACTURA_ENVIADO_SUSALUD = 17
    ESTADO_ENVIADO_IPRESS = 18

    # Conjunto de estados válidos
    ESTADOS_VALIDOS = {
        ESTADO_APROBADO_MA,
        ESTADO_OBSERVADO_MA,
        ESTADO_LIQUIDADO,
        ESTADO_EMPAQUETADO,
        ESTADO_ENVIAR_IAFAS,
        ESTADO_FACTURA_ENVIADO_SUSALUD,
        ESTADO_ENVIADO_IPRESS
    }