version: '3.8'

networks:
    spark_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.19.0.0/16"
services:
    spark:
        build: 
            context: .
            dockerfile: Dockerfile
        networks: 
            - spark_network
        ports:
            - '8080:8080'
            - '8000:8000'
        volumes:
            - .:/src