version: '3.8'

networks:
    spark_network:
        driver: bridge

services:
    spark-protecta:
        container_name: spark-validator-protecta
        build: 
            context: .
            dockerfile: Dockerfile
        networks: 
            - spark_network
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - '8081:8080'
            - '8001:8000'
        volumes:
            - .:/src