version: '3.8'

networks:
    spark_network_protecta:
        driver: bridge

services:
    spark-protecta:
        container_name: spark-validator-protecta
        build: 
            context: .
            dockerfile: Dockerfile
        networks: 
            - spark_network_protecta
        ports:
            - '8081:8080'
            - '8001:8000'
        volumes:
            - .:/src