[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10

[program:redis]
command=redis-server --port 6379
autostart=true
autorestart=true
startretries=3
stdout_logfile=/var/log/supervisor/redis.log
stderr_logfile=/var/log/supervisor/redis.err

[program:spark-master]
command=/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
autostart=true
autorestart=true
startretries=3
stdout_logfile=/var/log/supervisor/spark-master.log
stderr_logfile=/var/log/supervisor/spark-master.err

[program:celery-worker]
command=/home/markillat/Workspace/spark-validator-protecta/venv/bin/celery -A tasks worker --loglevel=info --concurrency=1
directory=/src
autostart=true
autorestart=true
startretries=3
stdout_logfile=/var/log/supervisor/celery-worker.log
stderr_logfile=/var/log/supervisor/celery-worker.err

[program:uvicorn]
command=uvicorn main:app --host 0.0.0.0 --port 8000
autostart=true
autorestart=true
startretries=3
stdout_logfile=/var/log/supervisor/uvicorn.log
stderr_logfile=/var/log/supervisor/uvicorn.err

#[program:spark-worker-1]
#command=/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark:7077
#autostart=true
#autorestart=true
#startretries=3
#stdout_logfile=/var/log/supervisor/spark-worker-1.log
#stderr_logfile=/var/log/supervisor/spark-worker-1.err

#[program:spark-worker-2]
#command=/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark:7077
#autostart=true
#autorestart=true
#startretries=3
#stdout_logfile=/var/log/supervisor/spark-worker-2.log
#stderr_logfile=/var/log/supervisor/spark-worker-2.err